name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Your Code
        uses: actions/checkout@v2
        
      - name: Check executable
        run: chmod +x ../../hello.sh

      - name: run script
        run: ./../../hello.sh